### ISSUE TITLE
Crash on PvP

### ISSUE THREAD

**Issue by Damgam** [kyranf/robotarmyfactorio#101]
http://i.imgur.com/72ajDIT.png
happen when you try to start match on PvP scenario

**Comment by kyranf** [comment]
What other mods are on? What scenario is it? Did it happen when only player 1 was in the game or when player 2 joined? 

-------- Original message --------

**Comment by Damgam** [comment]
only Robot Army and Creative Mode.
when you start PvP scenario you have "lobby" map. when you set everything you click "start" and then battle map appear... it's creating new forces at this moment... we were 2 on the map and this happened when i clicked "start" to generate battle map (i guess it's something with forces)

**Comment by kyranf** [comment]
@Damgam  thanks, i'm probably missing some new tables that should be instantiated during the "on_force_created" event but are being missed, and then later when all forces are iterated through to check for tick updates, the force doesn't have a tick table yet.

**Comment by kyranf** [comment]
I was able to reproduce it instantly by using:
/c game.create_force("test_force") 

while playing, it's definitely some missing code in the on_force_created event which should be making some of the new tables but clearly isn't.

**Comment by kyranf** [comment]
Turns out it was the handleForceCreated event handler was running but the input (the new force object) wasn't being used properly, so all the code after that (which was fine) was not doing what it was meant to!

**Comment by Damgam** [comment]
Thanks :)

**Comment by kyranf** [comment]
appears fixed, no more bugs reports related to this since.
