### ISSUE TITLE
make Hybrid targeting (#3) the default

### ISSUE THREAD

**Issue by petergaultney** [kyranf/robotarmyfactorio#109]
I tend to think Hybrid targeting is a better default than "closest enemy first". The screenshot I'm linking here shows that I have a Squad (using default targeting) way up in the top right corner of the map, whereas the nearest droid assembler (and outpost/base) is all the way in the bottom left. And my terminator droids have completely ignored a number of enemy bases in between, just because they think that the most important thing to do is attack whatever they're closest to.

https://www.dropbox.com/s/1pwrudi0a7bhrh6/Screenshot%202017-05-03%2019.48.29.png?dl=0

In fact, I can't think of any particular reason why a user of this mod wouldn't prefer their droids to keep the areas around their droid assemblers clear, rather than wandering off into the far-flung wilderness. Hybrid targeting doesn't prevent droids from continuing to search for targets when everything near the assembler is dead - it just causes them to prioritize it. And that's a win-win as far as I can see.

**Comment by kyranf** [comment]
Agreed, will change it to default in next version

**Comment by kyranf** [comment]
in 3.3 in unstable this is default. pending user feedback, this may not end up being desirable. I found squads rubber-banded a bit when it was better if they just stayed there and kept killing.
