### ISSUE TITLE
Robots Freeze When Hunting Squad Set to 20

### ISSUE THREAD

**Issue by bcrotty** [kyranf/robotarmyfactorio#117]
I set my hunting squad size to 20, and the robots behave normally when the squad is forming. Once the squad size reaches 20, all the robots just freeze in place. It seems to work normally when the squad size is at 10.

**Comment by kyranf** [comment]
can you get a screenshot of your spawning area these robots are in? And how far away is the nearest enemies that they would be trying to path towards?  What version of robot army are you using 0.3.2?  have you changed any settings in the  config.ini file?  

potentially a save file zip could be handy for me to test on as well

**Comment by kyranf** [comment]
the droid counter signals are global, but i would like to make a system where you attach a 'squad composition' module which is just setting the number of each type you want in a squad from that assembler, and let the assemblers take any robot type item as inputs (probably just make the assembler a fancy skinned chest that has the spawning script run on the inventory). 

So basically, you cannot set a 'terminator = 20' signal and attach it and make it spawn 20 terminators.. the 'terminator' signal in that situation is just an output-only signal from the counter module, and yes it's global.

**Comment by kyranf** [comment]
if you only spawned terminators from one assembler you could use inserter logic signals to only insert new terminators for spawning into the assembler when the global count is less than what you wanted.. but yeah the current system is difficult to do that.

**Comment by bcrotty** [comment]
Awesome. Thanks! Also, how do you use the squad command tool? I can select squads, but how do I tell them to do something?

**Comment by kyranf** [comment]
after selecting them, the squad will turn green. you can then give them an attack-move style command on the map screen (which is really fun! and you can select from the map view as well) or in the normal game screen,  using  SHIFT + LEFT CLICK.

**Comment by kyranf** [comment]
the selection is based on clicking near the 'center' of the squad, and looks for closest squad within a certain selection radius (i think it was 30 tiles). The squad 'center' can be seen in the debug view "view unit group info" if you are having troubles working out why a squad isn't being selected properly. Trying to select an individual who is separated from his group doesn't work, for example. 

You can use the squad pick-up tool (the red one) to drag-select and instantly pick up droids, which also works at infinite distance from the map screen.

**Comment by bcrotty** [comment]
Awesome, thanks for the help!
