### ISSUE TITLE
Warning Suppression

### ISSUE THREAD

**Issue by Moggers** [kyranf/robotarmyfactorio#120]
Would be nice if `config.lua` had an entry to suppress warnings, perhaps an array of event types to suppress warnings of. Particularly out of space, squad is no more, squad selection.
We're getting spammed with notifications of factory being out of space. I could provide a PR for this if you'd like.

I'm not sure if attempting to spawn so many bots that it triggers these warnings is actually expected behavior, the squads get up to the realm of 30-35 bots (with a squad size of anything from 10 to 30) since there are no surrounding biters for them to hunt, and previously it would stop at a bit over the current squad hunt size. Previously stopping at that limit would often cause multiple spawners to create two half size squads then stop, and never actually reaching the squad hunt size in either of the created squads. So I'm not reporting that as a bug due to the new behavior seeming to be a lot better (chat spam not withstanding).

**Comment by kyranf** [comment]
Hi Moggers,

For now, feel free to search the code for the strings with those chat messages and comment the lines out.

config.lua can certainly have some flags for enabling/disabling verbose errors/warnings, if you want to add the lines in there and the logic checking around each spam message then I would appreciate a PR that implements this.  Otherwise I can do it (eventually, i'm unfortunately pretty darn busy these days :(  )

**Comment by Moggers** [comment]
I'll look into it in that case.

**Comment by kyranf** [comment]
In my recent additions to the Unstable branch, i have fixed the hybrid targetting mode and also suppressed/removed the "cannot place droid, too many or obstructions" message. the assemblers normally spam that message when there is  >= 1.5x the squad hunt size worth of droids within 30 tile radius of the assembler. I found that while making squads act as guards, or with a short hunt range and no enemies nearby, the assembler would quickly get to this situation and begin spamming. 

It's good enough to just remove it.  The squads dieing is a config param already, you can see it in the config file "PRINT_SQUAD_DEATH_MESSAGES" make this = 0  to remove those messages.

**Comment by kyranf** [comment]
in 0.3.4 which is now released, i have removed the spam when assembler has reached the 1.5x squad size in nearby area to stop spawning
