### ISSUE TITLE
Multiplayer game fails with "Error while running event robotarmy::on_built_entity" 

### ISSUE THREAD

**Issue by blubFisch** [kyranf/robotarmyfactorio#122]
Nice mod, good job!

When I'm placing the Droid Assembler in the vanilla pvp multiplayer scenario, it crashes with
> Error while running event robotarmy::on_built_entity (ID 6)
> robotarmy/robolib/robotarmyhelpers.lua:566: attempt to index field '?' (a nil value)

I couldn't reproduce it when I loaded the game in singleplayer. In another multiplayer game (without other mods), it worked.

**Comment by kyranf** [comment]
interesting, i'll check it out thanks for the bug report. 

It looks like the "global.AssemblerNearestEnemies[force.name]" table is never created in the case where your error occurred, but DID happen in some other cases - so the initializers are inconsistent. I'll add a check to the table access to see if it's empty first and this should fix your problem.

**Comment by kyranf** [comment]
Your bug has been fixed in 0.3.4

**Comment by blubFisch** [comment]
Thanks, haven't had it since.
