### ISSUE TITLE
if military is already researched when the mod is installed, the recipes do not become available

### ISSUE THREAD

**Issue by TankFox** [kyranf/robotarmyfactorio#126]
I'm seeing another issue; military was already unlocked up to military 2 on my map when I installed the mod, but I can't actually build anything. The recipes aren't unlocked

This is such a great mod by the way!!!! I've been a fan for a long time!

**Comment by kyranf** [comment]
As a quick fix are you okay with using a few console commands? I'll paste them here to unlock the recipes that you are missing which would normally trigger when the research is done

**Comment by TankFox** [comment]
yes!

**Comment by kyranf** [comment]
for recipes supposed to unlock with Military 1:
`/c game.player.force.recipes["droid-rifle"].enabled=true`
`/c game.player.force.recipes["droid-rifle-deploy"].enabled=true`
`/c game.player.force.recipes["patrol-pole"].enabled=true`
`/c game.player.force.recipes["droid-guard-station"].enabled=true`
`/c game.player.force.recipes["droid-assembling-machine"].enabled=true`

For recipes supposed to unlock with Military 2:
`/c game.player.force.recipes["droid-smg"].enabled=true`
`/c game.player.force.recipes["droid-smg-deploy"].enabled=true`
`/c game.player.force.recipes["droid-rocket"].enabled=true`
`/c game.player.force.recipes["droid-rocket-deploy"].enabled=true`
`/c game.player.force.recipes["droid-flame"].enabled=true`
`/c game.player.force.recipes["droid-flame-deploy"].enabled=true`

for recipes supposed to unlock with Military 3:
`/c game.player.force.recipes["terminator"].enabled=true`
`/c game.player.force.recipes["terminator-deploy"].enabled=true`

for recipes supposed to unlock with Electronics:
`/c game.player.force.recipes["droid-counter"].enabled=true`
`/c game.player.force.recipes["droid-settings"].enabled=true`

for recipes supposed to unlock with Combat Robotics:
`/c game.player.force.recipes["defender-unit"].enabled=true`
`/c game.player.force.recipes["defender-unit-deploy"].enabled=true`
`/c game.player.force.recipes["distractor-unit"].enabled=true`
`/c game.player.force.recipes["distractor-unit-deploy"].enabled=true`
`/c game.player.force.recipes["destroyer-unit"].enabled=true`
`/c game.player.force.recipes["destroyer-unit-deploy"].enabled=true`

**Comment by TankFox** [comment]
Could you also post commands for Droid Pick Up Tool and Command Tool? They didn't fire either

**Comment by kyranf** [comment]
Edited commands above, under military 1 to include the pickup and selection tools. sorry! 

I have this issue ready to fix in an automatic way in the next release, sorry about this inconvenience

**Comment by TankFox** [comment]
no problem! I love your work! Thank you so much!!!
