### ISSUE TITLE
how to disable one force?

### ISSUE THREAD

**Issue by RubenNL** [kyranf/robotarmyfactorio#128]
i have the mod https://mods.factorio.com/mods/Nebual/TheyreMadeOutofMeat Theyre Made Out Of Meat installed.

this mod adds one force, for bots.

the problem is that they are getting attacked. how to disable this?

**Comment by kyranf** [comment]
The mod maker needs to set the player force to friendly (cease fire mode) with the bot force when the bot force is created

**Comment by RubenNL** [comment]
Okay, so that means i can close this issue and report it on the other mod.

**Comment by kyranf** [comment]
Yeah that's the best solution. I could do things on my end like setting all non-biter forces to friends at various times but that would break my mod in PvP scenarios which need more enemy forces than just the biters.
