### ISSUE TITLE
Updatet version?

### ISSUE THREAD

**Issue by RAJensen** [kyranf/robotarmyfactorio#150]
Hello.

Me and my game buddy did a test last night with this mod against the new 0.17.2 Factorio version. Unfortunately the mod does not seem to work with the new version.

So are there any plans to  make the mod working with the ned Factorio version? 

In advance Thank you for a great mod.

**Comment by kyranf** [comment]
I will be updating the mod to work with 0.17 as soon as I can, I'm on holiday and don't have very good internet connection in rural Australia right now but I should be able to make some progress (starting with actually getting 0.17 installed) on Sunday.

**Comment by RAJensen** [comment]
Hi Kyran.
It's sounds great.
We will be looking forward to it. :-)

**Comment by kyranf** [comment]
It's ready, find it on the mod portal. :)

**Comment by RAJensen** [comment]
Thank you.
That is great. :-)
Me and my gamebuddy just startet a new game yesterday in 0.17.2. :-)

**Comment by kyranf** [comment]
you can add it to the game now if you want, there's no problem adding to a game already started

**Comment by RAJensen** [comment]
Hi Kyran.

I have been tetstet the mod in real game life and i think it's time for an upgrade.
I'm only using Terminators and they are getting killed as fast as they move to the biterbase. :-(
I put 100 out and they where gone in 10 seconds!
They get killed by the toxic slime from worms in holes and the ones that is running around.
Maybe they need some more health or resistens against the slime? Also learn them to drive around the toxic slime could help them a lot.
At this moment the use of them has fallen to the ground.
So an upgrade, so they can come back in game and do a diffrence as in 0.16 is much appreciated. :-)

**Comment by kyranf** [comment]
What  is your Biter Evolution %? 

I think the new changes and damage types do need fixing in the mod, I will do some testing and try to fix it for you :) 

The new damage types for the worm and spitter attacks I think are not in the old resistances for the Robot Army units, so they do a lot of damage

**Comment by kyranf** [comment]
For short term fix, please open your mod's config.lua (in mod zip/folder, then "config" folder) and change HEALTH_SCALAR to  = 2.0. Save and launch your game and all your Robot units will have x2 health. This will help a little bit..

**Comment by kyranf** [comment]
it turns out the Acid attacks from worms and spitters doing damage every tick is too over-powered and the robot army units can't be balanced properly against it, so the next robot army update will disable acid per-tick damage from the biter units and worms.  Klonan had to do this for his Total Automization mod too.
