### ISSUE TITLE
missing player.png

### ISSUE THREAD

**Issue by antisocialian** [kyranf/robotarmyfactorio#159]
![image](https://user-images.githubusercontent.com/2091667/57100026-ec5ad180-6ceb-11e9-982a-ec9ae9d88ad1.png)

getting the above error when loading with v 0.17.35 (it just updated)

changelog says
`- Renamed the character entity type and name from "player" to "character" to make it consistent with how we call/access it in all other places.`
I assume just a name change is needed, but i haven't looked at the code to see.

**Comment by kyranf** [comment]
Correct, it's just a name change needed. They broke A LOT of mods with this one.

**Comment by kyranf** [comment]
All I can say for now, is you should roll back to 0.17.34 until further notice. It will take me until the weekend to finish all the juicy new features and stuff I have lined up for the next update, which will include the fix for this new problem from 0.17.35

**Comment by kyranf** [comment]
Okay, hot fix uploaded. works fine in 0.17.36. Enjoy!

**Comment by kyranf** [comment]
https://mods.factorio.com/mod/robotarmy/downloads
