### ISSUE TITLE
Failed to start a new game.

### ISSUE THREAD

**Issue by SashaIndustries** [kyranf/robotarmyfactorio#161]
New to Github so sorry if I miss format this.

Got an error on starting a new game.

Game version: 0.17.42

![Screenshot_151](https://user-images.githubusercontent.com/50889637/58133046-c2296f00-7c1a-11e9-8c87-45be302e813a.png)

Also might be worth saying I have over 100 mods enabled

**Comment by kyranf** [comment]
Do you have Biter Factions mod enabled?

**Comment by SashaIndustries** [comment]
Yes enabled and up to date does that cause this mod to fail?

**Comment by kyranf** [comment]
Yes, Biter Factions (which funnily enough is my mod too) makes a bunch of new factions and the code in Robot Army can't handle that properly in the current released version. I've fixed it in the next version but that isn't coming out for a few days/weeks yet. 

I recommend turning off biter factions mod for now.

**Comment by SashaIndustries** [comment]
No worries probably will turn off robot army and sorry for late reply.
Been trying to get my Factorio mod pack under control gone so far as to disable all my cores except for 2 then overclocking to 5.2GHz just to give factorio raw single thread performance.

**Comment by kyranf** [comment]
okay, that's fine. you can always add robot army later while the game is ongoing.  When v0.5.0 comes out with the host of other changes/additions, it will fix this issue you were having.

**Comment by kyranf** [comment]
This should be fixed long ago with code added after this issue was created.
