### ISSUE TITLE
Robot Army Path finding issues in latest 18.x / 26 [Causes Crash]

### ISSUE THREAD

**Issue by X-Niter** [kyranf/robotarmyfactorio#168]
I have attached the logs to show what is causing the crash. 
It has been proven that it has been a cause of adding robot army as I just now added it to my Krastorio 2 pack and within 10 minutes of building and deploying bots, the game crashed. 

[factorio-current.log](https://github.com/kyranf/robotarmyfactorio/files/4678229/factorio-current.log)

**Comment by kyranf** [comment]
Please upload this report and save game to the factorio developers, there
is a crash caused by their pathfinder algorithm code which is not a normal
mod script error, this is a more important bug/code issue they need to look
at.

Thanks!

**Comment by X-Niter** [comment]
Sorry for the late reply, I tend to not always get the greatest notifications for GitHub as may like. 
As I know Factorio Beta is now at 18.30 + // I will still go ahead and take this report over to them to see if there is a potential issue that could still be around. 
I will also run the test on 18.30 + to see for my self if it is something that happens in the latest version. 
Thank you for your help, Great and fun mod! I hope you keep up the great work chief!

**Comment by kyranf** [comment]
Thanks. let me know what happens!
