### ISSUE TITLE
error on spawning a the first robot on tick event

### ISSUE THREAD

**Issue by BlackRece** [kyranf/robotarmyfactorio#170]
![image](https://user-images.githubusercontent.com/19497851/87874895-63e65080-c9c5-11ea-8d7c-f8af0814cf82.png)

I added robo army and unit control with Factorio Extended and Factorissimo and got the error message depicted above.

other mods are as follows;
![image](https://user-images.githubusercontent.com/19497851/87874969-e7a03d00-c9c5-11ea-8a75-3ef9be9b7e9a.png) ![image](https://user-images.githubusercontent.com/19497851/87874977-f555c280-c9c5-11ea-810f-8c448711616a.png) ![image](https://user-images.githubusercontent.com/19497851/87874985-030b4800-c9c6-11ea-803f-b4be845e1e97.png)

**Comment by BlackRece** [comment]
as a note, i can manually build/plant bots, but i can't automate them using the buildings/factories provided.

**Comment by kyranf** [comment]
Hello, I will push a hotfix for this today. It's an ongoing issue since Factorio v0.18.27 I believe.  For term fix is downgrade to v0.18.26 or wait for my hotfix.

**Comment by kyranf** [comment]
I have a patched version 0.4.5 released now which deals with this. https://mods.factorio.com/mod/robotarmy/downloads
