### ISSUE TITLE
Make it possible to share with 'Reverse-Factory'mods from Kryzeth and' Z Recycling ' from DRY411S ?

### ISSUE THREAD

**Issue by Varoga** [kyranf/robotarmyfactorio#176]
Make it possible to share with 'Reverse-Factory'mods from Kryzeth and' Z Recycling ' from DRY411S ?

**Comment by Varoga** [comment]
Make it possible to share with 'Reverse-Factory'mods from Kryzeth and' Z Recycling ' from DRY411S ?

**Comment by kyranf** [comment]
hello, do you mean for the droid units and buildings to be recycled into original materials?

**Comment by Varoga** [comment]
These mods are incompatible. They give an error. I want them to work together.

**Comment by Varoga** [comment]
[locale.zip](https://github.com/kyranf/robotarmyfactorio/files/6997270/locale.zip)
Russian translation.

**Comment by kyranf** [comment]
Thank you for the russian translation! I have put that in the soon to be release 0.4.12 and put your name in the credits.

**Comment by kyranf** [comment]
can you show me a screen shot for the error you get? It looks like these recycling mods should work without errors

**Comment by Varoga** [comment]
[factorio.zip](https://github.com/kyranf/robotarmyfactorio/files/7080770/factorio.zip)
Screenshots from the screen.

**Comment by kyranf** [comment]
so that others viewing this don't have to download the zip file, here's the pictures Varoga showed:
![factorio_1](https://user-images.githubusercontent.com/7900774/131435899-f876cf72-9eae-44c9-8450-91f585c55837.PNG)
![factorio_2](https://user-images.githubusercontent.com/7900774/131435901-11dcf1c7-3d5f-432f-8121-fc30ce23e0e1.PNG)

**Comment by kyranf** [comment]
@Varoga   thank you, I am working with Kryzeth on a solution... https://mods.factorio.com/mod/reverse-factory/discussion/612b3f3ec3c4cb7224563957

**Comment by Varoga** [comment]
Hi, kyranf. I'm sorry, I made a mistake. This is due to my inattention. I accidentally installed the "Schall Main Battery" mod from Schallfalke, and it was he who caused the error between the "robot army" mod and the resource recycling mods. Thank you for not refusing to help.

**Comment by kyranf** [comment]
Thanks @Varoga . At least I got the russian translation files :) I will be putting out V0.4.12 today with improvements to droid combat AI and with Brazilian and Russian languages
