### ISSUE TITLE
The robot will stand in a daze and ignore nearby enemies

### ISSUE THREAD

**Issue by klarkxy** [kyranf/robotarmyfactorio#184]
![image](https://user-images.githubusercontent.com/6316992/233395267-dcc800b2-0be1-4311-bc93-b53c62a6f33d.png)

**Comment by kyranf** [comment]
Sometimes the biter AI for the bots does this, I  can't really fix that as it's an engine issue.  In the latest v2.x release I did some adjustments to reaction targeting and squad re-ordering frequency which may help a  little bit.
