### ISSUE TITLE
droids are getting hit by trains

### ISSUE THREAD

**Issue by kyranf** [kyranf/robotarmyfactorio#32]
need a new AI script that checks for squads adjacent/on train tracks and moves them away from it, while in "assembling" or "guard" mode (or others?)

**Comment by arrdem** [comment]
I've had a whole bunch of robots get nailed by trains when pathing along rails towards objectives.

**Comment by kyranf** [comment]
there's not an easy or CPU-efficient way for me to check this problem though. Iterating through each droid to check the tile under them for rails, even occasionally, will tank performance. I don't know if I'll be able to reasonably handle this issue @arrdem

**Comment by kyranf** [comment]
Can't reasonably do anything about this (yet), closing for now.
