### ISSUE TITLE
all squad AI is done at once on n'th tick - need time mux

### ISSUE THREAD

**Issue by kyranf** [kyranf/robotarmyfactorio#34]
need to create and maintain a "task" list which is a portion of squads in a force.

every tick, do at least one squad's AI routines, rather than possibly hundreds of squads all at once on the nth tick. This will definitely fix the lag "spike" issues.

**Comment by kyranf** [comment]
AI scheduler algorithm - new global table for each force, called "AI tasks" which has 60 entries - one for each tick. When a squad is created, its ID can be assigned to the tick-entry with the least number of current tasks assigned. Eventually, after 60 squads all 60 tables will have at least 1 squad to attend to on the specific tick with a 1 second (60 tick) period for repeating. As more are added, we assign them again to the tables with least amount, starting from the top. 

As squads die, and their squadref table entry is made nil, we must purge the equivalent reference from the AI scheduler tables. This way we get an almost round-robin style CPU load across each tick. 

In the conditions where squads die unequally and the task schedule tables become unbalanced over time, then a maintenance routine will be needed to occasionally re-balance the tables and therefore slightly adjust which tick the squad AI will be handled. This is optional, but for long-term cleanliness of the tables and the whole point of spreading the load, it's useful.

**Comment by Rockstar04** [comment]
Just throwing out an idea.

Could you push tasks into a table with a last processed time, and then just process the "oldest" task every tick? I'm not very familiar with Lua, so I'm not sure if the sort/select operations would present a performance issue or not. This approach would work around your need for a re-balance task, and could reduce the complexity of the scheduling system overall.

**Comment by kyranf** [comment]
constantly popping/pushing tasks onto a table like that, as if they were variables on a stack, is not memory effecient.. Or if you mean just keep an N length table but with a tick value for each one, and using a "sort" on that element to find the "oldest" tick task and only process that this tick is also slow. It also means that as the list progresses in size, the number of tasks = number of ticks before it gets back to task 1. 

Perhaps the task list can just be the last of tasks, their last executed tick, and this is just compared with the current tick count to see if it's time to run them, no matter what tick it is or how many other tasks will end up running on that tick. It's super unlikely that any large number of tasks will end up on any particular tick, but any kind of synchronous spawning like from assemblers might stack the tasks.. 

As long as the tasks can be organised in a way that doesn't need large re-allocation of table memory, or "sort" operations, then it should be fast enough..

that's why I was contemplating adding a 60-entry table, with each table being another table of tasks which are actually just the key (squad ID) of the squad whos AI needs to be run on this tick. 

it's ugly and complex but that's what optimisation is all about.. to just "get something working" i could totally just store tasks sorted by last tick and use "sort" to get the oldest (lowest tick). Perhaps doing that, and getting the length of the task list and just using modulo 60 to get how many tasks in the list to process will ensure all tasks are completed in a 60-tick loop? Oh, the possibilities! Programming is fun isn't it :0

**Comment by kyranf** [comment]
Closed, thanks to Peter
