### ISSUE TITLE
Modular Robot Manufacturing

### ISSUE THREAD

**Issue by lordnox** [kyranf/robotarmyfactorio#40]
Recently I started playing with this mod and I had an Idea that might be worth thinking about:

Change the build-process of the Bots to have multiple slots:
- Weapon-Slot
- Defense-Slot
- AI-Slot

Currently there are 4 bots in your mod:
Clockwork Riflebot : Pistol - Iron Armor - Basic-AI
Battle Droid : Submachine Gun - Heavy Armor - Basic-AI
Rocket Bot : Rocket Launcher - Heavy Armor - Basic-AI
Terminator : Laser Turret - Modular Armor - Basic-AI

Weapon Slot: 
- needs to be a Hand-Weapon for the player, or a Turret-type (something that has a range and a shooting method)
- Maybe later on changes the sprites used for the weapon

Defense Slot:
- needs to be an Armor
- will change the used Sprite (either from the amount of hitpoints, or the armor-name itself)

AI-Slot : 
- changes pathfinding
- changes shooting distances
- possibilities: default, scout, leader, healer, sniper, melee?

Again, I don't know enough of the factorio mod interna to really know how much (extra?) work this would create. The option this would allow you is to have other modders use your base and create their own turrets, guns and armor, or even AI modules, and have them simply work with the robot army.

Problems and imbalances I see:
- Ammunition : From magazines to fuel for the flamethrowers.. might be imbalanced

Thanks for your mod!

**Comment by kyranf** [comment]
The issue with Factorio is units are very specifically defined, so you can't really have proper modular units, but we can design the "parts" that are required in their recipes to give the impression of modular robot units. See my brainstorming here: https://github.com/kyranf/robotarmyfactorio/issues/36
