### ISSUE TITLE
Minor Issue with artifact loot/surface

### ISSUE THREAD

**Issue by Nexela** [kyranf/robotarmyfactorio#43]
[https://github.com/kyranf/robotarmyfactorio/blob/master/robolib/Squad.lua#L402](url)

What happens if you are on a surface other than the default and want to pick up artifacts :)

**Comment by kyranf** [comment]
Quite a lot of the mod only supports the Nauvis surface. This was done on purpose to reduce the code required and can always be added later. 
Now that mods like Factorissimo and the various "underground" mods are becoming more popular and it's more likely for droids to exist in other surfaces, I may revisit all the uses of surfaces in the mod and adjust them to make it work on whatever surface the squad is on. 


-------- Original message --------

**Comment by kyranf** [comment]
fixed in 0.2.1 dev branch
