### ISSUE TITLE
Unhandled exception (error Notice) on placing rally point before any robots were placed in the game

### ISSUE THREAD

**Issue by msu320** [kyranf/robotarmyfactorio#49]
![robot-army](https://cloud.githubusercontent.com/assets/17893039/17317452/df0981d2-584b-11e6-887b-7965413722b4.jpg)

text reads: Error while running the event handler: control.lua:357: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by kyranf** [comment]
Hi, yes this issue was reported and fixed for 0.2.1 release in a few days. You can get the dev branch and use that for now if it bothers you. It happens because placing a rally point before any droid has been placed is not expected and wasn't properly handled in my code. Sorry about that!

**Comment by kyranf** [comment]
Fixed in 0.2.1 dev branch
