### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by bonzai1102** [kyranf/robotarmyfactorio#54]
Hi.
I got this Error after updating to Robot Army 0.21
Factorio Version: 0.13.14

> Error while running the on_configuration_changed: __robotarmy__/control.lua:143: attempt to index field 'droidGuardStations' (a nil value)

**Comment by kyranf** [comment]
Hi @bonzai1102  can you please download this updated mod https://github.com/kyranf/robotarmyfactorio/archive/Development.zip  

And see if that fixes your game?

**Comment by bonzai1102** [comment]
That works. Thank you.
