### ISSUE TITLE
Event handler Robot Army errer

### ISSUE THREAD

**Issue by CapnTRJ** [kyranf/robotarmyfactorio#56]
Playing  Factorio 0.13.5 on steam with a few mods installed and I get this error. 
"Notice
Error while running the event handler:
__robotarmy__/robolib/Squad.lua:105:
LuaUnitGroup doesn't contain key surface."

I am new to modding so I dont know exactly what this means or how to fix it. 

All mods i have are
Advanced Logistis, Auto Deconstruct, Auto Trash, Color Coding, EvoGUI, Factorio Reach,
Factorissimo, FARL, Larger Inventory, MoreLight, Rail Tanker, Robot Army, Resource Spawner Overhaul,
Upgrade Builder and Planner, Warehousing Mod, YARM.

**Comment by kyranf** [comment]
There are some serious bug fixes and mod scripting additions in Factorio versions above yours, you must update your game to at least 0.13.11 but it's best just to go straight to the latest 0.13.15.

**Comment by CapnTRJ** [comment]
Thank you.  That seems to have fixed it.  Should have thought of that earlier haha.

**Comment by kyranf** [comment]
No worries!
