### ISSUE TITLE
Robots can't use gates (I think?)

### ISSUE THREAD

**Issue by emichael** [kyranf/robotarmyfactorio#62]

**Comment by kyranf** [comment]
You are right, they can't it is a problem with the game pathfinding, there is nothing I can do. 

You can use this to your advantage though by making walls around your factory and using gates (like you normally would) for your self and trains to get in and out, and if you make droids on the outside of the walls they will not be able to go inside or through your base. 

This stop them from getting stuck on conveyor belts and your factory in general.

**Comment by kyranf** [comment]
Closing as it's an issue I cannot do anything about
