### ISSUE TITLE
60 droids ready, why don't they attack?

### ISSUE THREAD

**Issue by vanatteveldt** [kyranf/robotarmyfactorio#78]
Not sure if you want this here, on mods.factorio.com, or on the forums...

I've assembled 45 or so terminator bots from a single droid assembler, set squad size to 5 and hunting radius to 10k, but they refuse to venture out. Surely the base up north (see minimap) is less than 10k tiles away, right?

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/1736240/19188922/5da05d04-8c95-11e6-846e-01e66eacd48f.png)

(edit: after manually setting a rally point and removing it they did attack almost immediately and kept attacking other bases, any idea what is the problem?)

**Comment by kyranf** [comment]
Hi, thanks for the report. Can you confirm for me what version of the mod you are using, and what version of Factorio you are using? It does seem strange that they didn't automatically attack when they reached the squad size.  Where did you place the rally point?

**Comment by vanatteveldt** [comment]
Thanks for your response (and for making the mod, of course)! I placed the rallying point above the outpost, i.e. about halfway to the base. The problem repeated with a second squad, i.e. they just stayed there until I placed a rallying point. 

I tested the mod earlier in another location, there it seemed to work fine. The distance to the enemy bases should be fine in the screenshot above, right?

I'm using the latest experimental version of factorio and the robot army mod from the portal, version 0.2.3.

**Comment by vanatteveldt** [comment]
I experimented a bit more, and in other parts of the base they had no problems attacking. Can the water between the assembler and the nearest base be a problem?

**Comment by vanatteveldt** [comment]
Never mind, I think I got it figured out: there was a lone worm chilling out in the peninsula that is part of the outpost. I'm guessing that that was the nearest target, so they wanted to attack it, but couldn't path to it because of the outpost walls, and then just froze? 

After killing the worm, the bots went on the offensive after a couple seconds. 

Closing the issue, no idea if this behaviour is preventable, but at least now I think I understand it :)

**Comment by kyranf** [comment]
One way you can check to see if they have a path somewhere they cannot get to, is to use the F5 debug overlay with unit group info and path finder info all turned on (in F4 settings). You can see the squad's unit group circle, and it should show a dotted or slashed path line to their intended destination if they cannot get there. If they can get there, the path line will appear different.

**Comment by vanatteveldt** [comment]
Cool, I didn't know that; I haven't actually used the debug mode at all yet.

It turns out terminators have difficulty dealing with large 100%-evo bases, maybe I should create squads of 25 or so...
