### ISSUE TITLE
My robots will not hunt...

### ISSUE THREAD

**Issue by cpeosphoros** [kyranf/robotarmyfactorio#90]
![screenshot from 2016-12-13 10-09-15](https://cloud.githubusercontent.com/assets/748982/21140181/bf7fe690-c11d-11e6-91ee-7bde169cb085.png)
![screenshot from 2016-12-13 10-08-29](https://cloud.githubusercontent.com/assets/748982/21140194/d202e22c-c11d-11e6-82c1-9380a54fd1bf.png)

My hunting squad size is set to 40. As you can see, from the second screenshot, the droid count is over 100 and they are still not hunting.

Hunting radius is set to 1k. From the map screenshot, the white square of my base (courtesy of Concreep) is 275 tiles wide, so there are plenty of biters in a 1000 tiles radius, yet the guys are still loitering around their assembly.

I've just switched to dev branch. May be that is the issue.

**Comment by cpeosphoros** [comment]
Just as a follow up, I've tried "mining" them back and respawning, to no avail, still not going hunt. But funny thing is, when mining them, each one of them was in their own squads (it spamed me with "Squad nnn is no more" messages.)

**Comment by kyranf** [comment]
Are they completely surrounded with walls?

**Comment by cpeosphoros** [comment]
No, they have a long wall fencing then to the south and the east, so they would not wander over my belts (The blue lines on the Map, courtesy of "Useful Map Colors" mod, are the walls). With the regular Robot Army mod (non-dev branch), they were working fine - except for the usual pathfinding problems near water bodies.

First thing when I switched to dev branch was posting a rally point to the NW area shown in the second screenshot, about 30 tiles distant from the assembler. They broke the squad and came back by ones, as expected. Then, when they did not regroup, I mined them and respawned, which resulted in the reported issue.

In the regular branch, posting the rally point did not break the idling behavior near water - a known bug as I understand it.

I don't know if it's relevant, but I have them mass produced somewhere else in the factory and delivered to logistics requesters chests just south of the assemblers. There I have a fast inserter feeding them into each assembler, gated by wiring on the number of live droids. When I mine them, they are auto trashed and refed to the system.

**Comment by kyranf** [comment]
The rally point does mess with droids, try removing any rally points. Rally points pulse a move command every so often, and if the time is too fast before the squad gets a valid path, it re-starts their pathfinding request - causing an infinite loop.

**Comment by kyranf** [comment]
Rally points were disabled because they were a pain in the ass.  There is now a map-usable selection/command tool, and a map-usable pick-up tool if squads get stuck or you want to quickly recall large groups (drag selection works nicely)
