### ISSUE TITLE
Unbuilding droid assembler crashes the game

### ISSUE THREAD

**Issue by cpeosphoros** [kyranf/robotarmyfactorio#91]
![screenshot from 2016-12-13 10-40-50](https://cloud.githubusercontent.com/assets/748982/21140709/b9bfdc4e-c120-11e6-9f1e-3c3505f39d2c.png)

**Comment by kyranf** [comment]
Thank you, this is a bug and will be fixed today and committed to the dev branch. The code does not check for a "nil" assembler after trying to find an assembler by its ID in a list.

**Comment by kyranf** [comment]
Closed pending testing changes to Unstable branch. Code now checks for invalid/nil "assembler" variable before trying to check the entity "valid" value.
