### ISSUE TITLE
Crash event immediately after researching Logistics in a new save

### ISSUE THREAD

**Issue by cpeosphoros** [kyranf/robotarmyfactorio#92]
![screenshot from 2016-12-13 17-40-58](https://cloud.githubusercontent.com/assets/748982/21156007/6e50a19a-c15b-11e6-8d3b-9e311de9e4e3.png)

I'd just started a new game. Set up auto production for red science bottles and just finished researching Logistics. When I came out of the research complete science window, this crash came. I'd not built anything Robot Army related.

(Playing on dev branch).

**Comment by kyranf** [comment]
wow, RIP. maybe remove robot army mod until I fix it today. thanks for the bug report.

**Comment by cpeosphoros** [comment]
No problems, switched back to 2.3

**Comment by kyranf** [comment]
This bug should now be fixed, closing pending testing. Re-open if testing shows it is not fixed. Thanks for reporting it @cpeosphoros  !
