### ISSUE TITLE
Flame bot name error

### ISSUE THREAD

**Issue by Shilkwurm** [kyranf/robotarmyfactorio#93]
robotarmyfactorio/locale/en/locale.cfg

In this directory there is a missing line of text near the top for the flame dummy bot, as in game the name of the item is an error

droid-flame-dummy = Flame bot (deployable)

This is the code I think is missing, just made it based on how the other droids were written

**Comment by kyranf** [comment]
Hey I think I had already fixed this in the most recent branch?

**Comment by kyranf** [comment]
Please check-out/clone the Unstable branch and use that, to try out the various fixes. If you see any bugs during gameplay be sure to point them out :)

**Comment by Shilkwurm** [comment]
in 0.2.3?

**Comment by Shilkwurm** [comment]
also sorry i am a bit new to the development branches of things I just saw the in game name was unfinished and it triggered me a bit so I tried to do something about it or at least help do something

**Comment by kyranf** [comment]
@Shilkwurm  no, thank you for your enthusiasm!

**Comment by kyranf** [comment]
Closing because it's fixed in recent branches
