### ISSUE TITLE
Crash: attempt to index local 'squad' (a nil value)

### ISSUE THREAD

**Issue by thisismynombre** [kyranf/robotarmyfactorio#97]
This morning, I was messing around with destroyer droids.  I changed the squad size to 100, and the retreat size to 40, via the settings module. Then I setup a circuit between an activity module and an inserter arm to maintain a total army of 200.

The first group of 100 went off hunting just fine.  I left them alone for a while, and when I came back, I noticed that there were ~150 droids just buzzing around the assembling machine.  I tried using the rally point to get them all to reconnoiter, but only about half of them responded to the rally flag.  Then I started running around and picking them up.  While I was picking them up, I was getting a lot of "squad is no more messages."  After I had picked up like 50 of them, I got this error:

```
Error MainLoop.cpp:788: Exception at tick 5212150: Error while running event on_tick (ID 0)
__robotarmy__/robolib/Squad.lua:728: attempt to index local 'squad' (a nil value)
```

Log files:
[robot_army_logs.zip](https://github.com/kyranf/robotarmyfactorio/files/921978/robot_army_logs.zip)
[factorio-current.zip](https://github.com/kyranf/robotarmyfactorio/files/921977/factorio-current.zip)

**Comment by kyranf** [comment]
Thanks I'll look into it this weekend! Should be a quick fix. 


-------- Original message --------

**Comment by kyranf** [comment]
I updated the squad.lua file with a check that should fix the error you found. It was probably a rare case where a squad was removed in the same tick but before the artifact gather function was called,  with the squad now being nil by the time that function was called.
